### ISSUE TITLE
Babel 7 Support

### ISSUE THREAD

**Issue by c06e** [shrynx/babel-plugin-transform-dynamic-import-to-static#1]
Are there any plans to have Babel 7 support?

I'm getting the following error during build.

```
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'rawValue' of undefined
    at PluginPass.enter (C:\ws\Djanno\src\node_modules\babel-plugin-transform-dynamic-import-to-static\index.js:23:62)
    at newFn (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (C:\ws\Djanno\src\node_modules\@babel\traverse\lib\context.js:118:16)
```

**Comment by shrynx** [comment]
i didn't know if anyone else was even using it.
my usecase for this is no longer needed, but i'll see what i can do with it hopefully within this week

**Comment by c06e** [comment]
Thank you. Appreciate it.
